#define PORT_INVEN_MASK PORT_INVEN_bm

// STANDBY LED
#define STANBYLED_PORT PORTD
#define STANBYLED_DIR STANBYLED_PORT.DIR
#define STANBYLED_REG STANBYLED_PORT.OUT  // will be defined as OUT
#define STANBYLED_BIT PIN5_bp
#define STANBYLED_MASK PIN5_bm
#define STANBYLED_CTRL STANBYLED_PORT.PIN5CTRL

// POWER LED
#define POWERLED_PORT PORTD
#define POWERLED_DIR POWERLED_PORT.DIR
#define POWERLED_REG POWERLED_PORT.OUT  // will be defined as OUT
#define POWERLED_BIT PIN5_bp
#define POWERLED_MASK PIN5_bm
#define POWERLED_CTRL POWERLED_PORT.PIN5CTRL

// POWER BUTTON
#define POWERBTN_PORT PORTD
#define POWERBTN_DIR POWERBTN_PORT.DIR
#define POWERBTN_REG POWERBTN_PORT.IN  // will be defined as IN
#define POWERBTN_BIT PIN0_bp
#define POWERBTN_MASK PIN0_bm
#define POWERBTN_CTRL POWERBTN_PORT.PIN0CTRL

// AMP700 MODULE 1 CTRL PINS
#define AMP1_PORT PORTA
